// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocnitbmjzvyxnkzesome.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jbml0Ym1qenZ5eG5remVzb21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzU1OTcsImV4cCI6MjA2MjY1MTU5N30.P9REXunf3ipwpL8kLZUNQFnboI7x5ys4SyFCetnHyKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);